import unittest
import pandas as pd
import numpy as np
from datetime import date
import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.screener.portfolio.portfolio_optimizer import optimize_portfolio, aggregate_candidates, build_fallback_allocations
import src.screener.portfolio.portfolio_optimizer as optimizer_module

def mock_fetch_bulk_history(symbols, as_of_date, lookback_days=504):
    """
    Mock fetcher that generates dummy price data avoiding network calls.
    Returns 250 days of data ending at as_of_date.
    If symbol is MISSING_DATA, it returns only 10 days of data.
    """
    data = {}
    for sym in symbols:
        dates = pd.date_range(end=as_of_date, periods=250, freq='B')
        
        if sym == "MISSING_DATA":
            dates = pd.date_range(end=as_of_date, periods=10, freq='B')
            
        # Use deterministic seed per symbol
        np.random.seed(abs(hash(sym)) % (2**32))
        returns = np.random.normal(0.001, 0.02, len(dates))
        prices = 100 * np.exp(np.cumsum(returns))
        
        df = pd.DataFrame({"Close": prices}, index=dates)
        data[sym] = df
        
    return data

# Override the fetcher for tests
optimizer_module.fetch_bulk_history = mock_fetch_bulk_history

class TestPortfolioOptimizer(unittest.TestCase):
    
    def setUp(self):
        self.as_of_date = date(2026, 8, 11)
        self.base_candidate = {
            "symbol": "AAPL",
            "entry_price": 150.0,
            "stop_loss": 140.0,
            "target": 180.0,
            "strategy_name": "Test Strategy"
        }

    # Test 1: 5 valid candidates -> optimization feasible
    def test_5_candidates_optimization(self):
        candidates = []
        for i in range(5):
            c = self.base_candidate.copy()
            c["symbol"] = f"SYM_{i}"
            candidates.append(c)
            
        allocations = optimize_portfolio(candidates, self.as_of_date)
        
        # Verify no position exceeds 20%
        for alloc in allocations:
            if alloc["Symbol"] != "CASH":
                self.assertLessEqual(alloc["Target_Weight_Pct"], 20.0)
                
        # Total equity weights + cash weight should be approx 100
        total_weight = sum(a["Actual_Weight_Pct"] for a in allocations)
        self.assertAlmostEqual(total_weight, 100.0, places=1)

    # Test 2: 3 candidates -> fallback logic
    def test_3_candidates_fallback(self):
        candidates = []
        for i in range(3):
            c = self.base_candidate.copy()
            c["symbol"] = f"SYM_{i}"
            candidates.append(c)
            
        allocations = optimize_portfolio(candidates, self.as_of_date)
        
        # Check cash reason
        cash_alloc = next(a for a in allocations if a["Symbol"] == "CASH")
        self.assertIn("Max Position Constraint", cash_alloc["Cash_Reason"])
        
        # Check Max weight
        for alloc in allocations:
            if alloc["Symbol"] != "CASH":
                self.assertLessEqual(alloc["Target_Weight_Pct"], 20.0)
                
    # Test 3: 1 candidate -> fallback logic
    def test_1_candidate_fallback(self):
        candidates = [self.base_candidate.copy()]
        allocations = optimize_portfolio(candidates, self.as_of_date)
        
        cash_alloc = next(a for a in allocations if a["Symbol"] == "CASH")
        self.assertIn("Max Position Constraint", cash_alloc["Cash_Reason"])
        self.assertGreaterEqual(cash_alloc["Target_Weight_Pct"], 80.0)
        
    # Test 4: Duplicate symbol generated by 3 strategies
    def test_duplicate_symbol_consensus(self):
        c1 = self.base_candidate.copy()
        c2 = self.base_candidate.copy()
        c2["strategy_name"] = "Strat 2"
        c3 = self.base_candidate.copy()
        c3["strategy_name"] = "Strat 3"
        
        agg = aggregate_candidates([c1, c2, c3])
        self.assertEqual(len(agg), 1)
        self.assertEqual(agg[0]["strategy_count"], 3)
        self.assertEqual(agg[0]["strategy_consensus_score"], 0.60) # 0.50 + 0.05 * 2
        
    # Test 5: Candidate missing historical data
    def test_missing_historical_data(self):
        c1 = self.base_candidate.copy()
        c2 = self.base_candidate.copy()
        c2["symbol"] = "MISSING_DATA" 
        
        cands = [c1, c2]
        for i in range(4):
            c = self.base_candidate.copy()
            c["symbol"] = f"SYM_{i}"
            cands.append(c)
            
        allocations = optimize_portfolio(cands, self.as_of_date)
        symbols_in_alloc = [a["Symbol"] for a in allocations]
        self.assertNotIn("MISSING_DATA", symbols_in_alloc)
        
    # Test 6: Candidate missing confidence -> No KeyError
    def test_missing_confidence(self):
        agg = aggregate_candidates([self.base_candidate])
        self.assertIn("strategy_consensus_score", agg[0])
        
    # Test 9: Whole-share rounding math
    def test_whole_share_rounding(self):
        candidates = []
        for i in range(5):
            c = self.base_candidate.copy()
            c["symbol"] = f"SYM_{i}"
            c["entry_price"] = 333.33 
            candidates.append(c)
            
        allocations = optimize_portfolio(candidates, self.as_of_date)
        
        total_rs = sum(a["Allocation_Rs"] for a in allocations)
        self.assertAlmostEqual(total_rs, 1000000.0, places=1)
        
        for a in allocations:
            if a["Symbol"] != "CASH":
                self.assertAlmostEqual(a["Allocation_Rs"], a["Suggested_Shares"] * a["Current_Price"], delta=15.0)
                
    # Test 11: Deterministic repeatability
    def test_deterministic_repeatability(self):
        candidates = []
        for i in range(5):
            c = self.base_candidate.copy()
            c["symbol"] = f"SYM_{i}"
            candidates.append(c)
            
        alloc1 = optimize_portfolio(candidates, self.as_of_date)
        alloc2 = optimize_portfolio(candidates, self.as_of_date)
        
        self.assertEqual(alloc1, alloc2)

if __name__ == '__main__':
    unittest.main()
